console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
console.log("batata frita com lingruça toscana")
console.log("Outra vez sem ponto e virgula")
